### DISCUSSION TITLE
Constraint Select width for long item

### DISCUSSION THREAD

**Discussion by thewebartisan7** [radix-ui/themes#438] [Q&A] [answered]
What is best way to constraint select width? I am using Radix themes, and I see that the trigger has text-overflow ellipsis so I could just set a width to it like 

```css
.rt-SelectTriggerInner {
      max-width: 150px;
}
```

Is there a better way like some prop or css variable to do this?

Thanks
