### ISSUE TITLE
Cant override --color-background token

### ISSUE THREAD

**Issue by Hackjamin** [radix-ui/themes#168]
Hey Folks,

i tried to override the --color-background in a tokens.css of my next 13 / app router project. But it seems like it is resetting all the time.

The light mode should have a "beige" background, but the rendered html file still contains this:
```html
<style>
            :root, .light, .light-theme {
                --color-page-background: white;
            }

            .dark, .dark-theme {
                --color-page-background: var(--sage-1);
            }

            body {
                background-color: var(--color-page-background);
            }
        </style>
``` 

layout.tsx
```javascript
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Theme, ThemePanel } from '@radix-ui/themes'
import Footer from '@/components/Footer'
import './globals.scss'
import './tokens.css'
``` 

tokens.css
```css
@font-face {
  font-family: Montserrat;
  src: local('/fonts/Montserrat-Italic-VariableFont_wght.ttf');
}
.radix-themes {
  --default-font-family: 'Montserrat';
  --heading-font-family: 'Montserrat';
  --quote-font-family: 'Montserrat';
  --font-weight-light: 300;
  --font-weight-regular: 400;
  --font-weight-medium: 500;
  --font-weight-bold: 700;
}

:where(.radix-themes) {
  --color-background: beige;
  --color-overlay: var(--black-a6);
  --color-panel-solid: beige;
  --color-panel-translucent: rgba(255, 255, 255, 0.8);
  --color-surface: rgba(255, 255, 255, 0.9);
}
:is(.dark, .dark-theme),
:is(.dark, .dark-theme) :where(.radix-themes:not(.light, .light-theme)) {
  --color-background: var(--gray-1);
  --color-overlay: var(--black-a8);
  --color-panel-solid: var(--gray-2);
  --color-panel-translucent: var(--gray-2-translucent);
  --color-surface: rgba(0, 0, 0, 0.25);
}
``` 

or did i miss something here?
