### ISSUE TITLE
[Button] Issue - No options to enable Cursor Pointer

### ISSUE THREAD

**Issue by sakthivels87** [radix-ui/themes#202]
Hi @Radix Team,

Recently i have started using radix ui to one of my project. I have used buttons in many places of my web page. I have received feedback to enable the hand cursor for buttons. When i checked Radix ui documentation, am not able to see any options to enable hand cursor. 

Can you help me? How to enable hand cursor for buttons?

Thanks for producing this beautiful  radix/ui framework.

- Sakthi.

**Comment by kevinmitch14** [comment]
Check this out: https://github.com/radix-ui/themes/issues/123#issuecomment-1778862252

You can do something like the following.
```css
.radix-themes {
  --cursor-button: pointer;
}
```

**Comment by vladmoroz** [comment]
Yep, you’d do it like that with a CSS variable override ☝️ . We need to improve the docs on customizing Radix Themes to make this a bit more apparent. Here’s a common configuration that handles pointer cursors consistently:

```css
.radix-themes {
  --cursor-button: pointer;
  --cursor-disabled: default;
  --cursor-link: pointer;
  --cursor-menu-item: pointer;
  --cursor-slider-thumb: pointer;
  --cursor-slider-thumb-active: pointer;
  --cursor-switch: pointer;
}
```
