### ISSUE TITLE
TextField Chrome Incorrectly Applied

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#239]
It appears that the `outline` of the TextFieldChrome in the Chrome browser is incorrectly applied. And, if I am not off base, this would have implications everywhere where `outline` is defined in the same way.

#### Issue:
The TextField chrome is defined as:
```css
.rt-TextFieldChrome {
  ...
  :where(.rt-TextFieldInput:focus) + & {
    outline: 2px solid var(--color-focus-root);
    outline-offset: -1px;
  }
}
```

If I look at the applied class in DevTools it looks like:
<img width="322" alt="image" src="https://github.com/radix-ui/themes/assets/1885864/d94014b0-34d1-47d2-b4ee-f34b68b5d66a">
(Note that DevTools has no values assign to the expanded attributes)

If I change the definition to something like `2px solid blue`, DevTools correctly assigns the attributes:
<img width="322" alt="image" src="https://github.com/radix-ui/themes/assets/1885864/db513899-7e0c-4fd2-9b5b-64a4dee688b4">

The result of this issue is that no outline is applied (to at least `<TextField variant="soft" />`'s).

**This is definitely a bug with Chrome, or at least an inconsistency with what people would expect the specification to be.**

However, it is nonetheless an issue.

I think the fix would be to update `rt-TextFieldChrome` to:
```css
.rt-TextFieldChrome {
  ...
  :where(.rt-TextFieldInput:focus) + & {
    outline: 2px solid;
    outline-color: var(--color-focus-root);
    outline-offset: -1px;
  }
}
```

**Again, if I am not off base, I believe this would be an issue for any class attempting to assign outline attributes with the `outline` shorthand (which include variables).**
