### ISSUE TITLE
[Request] Add variable accent to color enum

### ISSUE THREAD

**Issue by trebitowski** [radix-ui/themes#33]
If a parent component has a color set, it is inherited by the children. This is useful in most cases, but I've found a few times I wanted to reset the component's color back to the theme accent. The way I've been accomplishing this is to override the color again on the child, but then it doesn't change with the theme accent

It would be nice to have a way to set a components color to match the theme color no matter what.

  

With no color specified on the link, it will be gray, inherited from parent callout
```TSX
<Callout.Root color="gray">
    <Callout.Icon>
      <InfoCircledIcon />
    </Callout.Icon>
    <Callout.Text>
      You will need <Link href="#">admin privileges</Link> to install and access
      this application.
    </Callout.Text>
  </Callout.Root>
```

We can override the link's color to violet, but it won't change with the theme
```TSX
<Callout.Root color="gray">
    <Callout.Icon>
      <InfoCircledIcon />
    </Callout.Icon>
    <Callout.Text>
      You will need <Link color="violet" href="#">admin privileges</Link> to install and access
      this application.
    </Callout.Text>
  </Callout.Root>
```

Proposed idea to be able to 'reset' the link's color back to the theme accent
```TSX
<Callout.Root color="gray">
    <Callout.Icon>
      <InfoCircledIcon />
    </Callout.Icon>
    <Callout.Text>
      You will need <Link color="accent" href="#">admin privileges</Link> to install and access
      this application.
    </Callout.Text>
  </Callout.Root>
```

**Comment by jd-carroll** [comment]
Sounds like a great addition 👍🏻

**Comment by vladmoroz** [comment]
Please see https://github.com/radix-ui/themes/issues/65

**Comment by kevinmitch14** [comment]
What about something like this, maybe a bit hacky. When you want to use color="accent", use color="gold" instead. I just picked god because I never use it.

```css
.radix-themes {
  --gold-1: var(--accent-1);
  --gold-2: var(--accent-2);
  --gold-3: var(--accent-3);
  --gold-4: var(--accent-4);
  --gold-5: var(--accent-5);
  --gold-6: var(--accent-6);
  --gold-7: var(--accent-7);
  --gold-8: var(--accent-8);
  --gold-9: var(--accent-9);
  --gold-10: var(--accent-10);
  --gold-11: var(--accent-11);
  --gold-12: var(--accent-12);

  --gold-a1: var(--accent-a1);
  --gold-a2: var(--accent-a2);
  --gold-a3: var(--accent-a3);
  --gold-a4: var(--accent-a4);
  --gold-a5: var(--accent-a5);
  --gold-a6: var(--accent-a6);
  --gold-a7: var(--accent-a7);
  --gold-a8: var(--accent-a8);
  --gold-a9: var(--accent-a9);
  --gold-a10: var(--accent-a10);
  --gold-a11: var(--accent-a11);
  --gold-a12: var(--accent-a12);

  --gold-surface: var(--accent-surface);
  --gold-indicator: var(--accent-indicator);
  --gold-track: var(--accent-track);
  --gold-contrast: var(--accent-contrast);
}
```

```tsx
const ACCENT_ALIAS = "gold";

<Badge color={ACCENT_ALIAS}>TESTING</Badge>
<Badge color={ACCENT_ALIAS} variant="surface">
  TESTING
</Badge>
<Badge color={ACCENT_ALIAS} variant="surface">
  TESTING
</Badge>
```
<img width="221" alt="Screenshot 2024-10-17 at 11 39 12" src="https://github.com/user-attachments/assets/5c412bb6-e224-402d-8eb5-a5b76d6bdae9">
