### ISSUE TITLE
[Spinner] Add different appearance variants

### ISSUE THREAD

**Issue by MiracleHorizon** [radix-ui/themes#412]
I'd like to suggest adding different appearance options for the Spinner. 
I think you could even add an option to choose a variant at the theme level, like with color, radius, to make it easy to unify this.

For example (but, I think you already know a lot of options):
![CleanShot 2024-03-25 at 12 52 37](https://github.com/radix-ui/themes/assets/90560240/8938d24b-fa3e-45de-b58e-447a965d8cc9)

**Comment by vladmoroz** [comment]
We don't have any immediate plans to bring this style into Radix Themes as it is a completely different vibe from the rest of the project, however it should be fairly easy to implement it yourself

**Comment by v1s10n-4** [comment]
Leaving this here in case it will be useful to someone.

I found a way to replace the spinner animation and preserve size, color, etc. We just have to hide the leaves and use an animated svg as mask.

```css
.rt-SpinnerLeaf {
  display: none;
}

.rt-Spinner {
  background-color: currentColor;
  image-rendering: pixelated;
  mask: url('data:image/svg+xml;utf8,<svg xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 7 7" xmlns="http://www.w3.org/2000/svg"><path d="M3,3 4,3 4,4 3,4" fill="black"><animate attributeName="d" dur="1s" repeatCount="indefinite" calcMode="discrete" values="M3,3 4,3 4,4 3,4;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M0,5 1,5 1,6 0,6M4,5 5,5 5,6 4,6M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M4,1 5,1 5,2 4,2M0,4 1,4 1,5 0,5M2,1 3,1 3,2 2,2M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M6,4 7,4 7,5 6,5M2,5 3,5 3,6 2,6M2,1 3,1 3,2 2,2M6,5 7,5 7,6 6,6;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3M6,4 7,4 7,5 6,5M2,1 3,1 3,2 2,2;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,2 3,2 3,3 2,3M4,4 5,4 5,5 4,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M1,2 2,2 2,3 1,3M5,4 6,4 6,5 5,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M1,3 2,3 2,4 1,4M5,3 6,3 6,4 5,4M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M1,4 2,4 2,5 1,5M5,2 6,2 6,3 5,3M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5M2,4 3,4 3,5 2,5M4,2 5,2 5,3 4,3;M3,3 4,3 4,4 3,4M3,2 4,2 4,3 3,3M3,4 4,4 4,5 3,5;M;"/></path></svg>');
}
```

I'ts not ideal but it works.
