### ISSUE TITLE
oklch. Consider output the value of lightness channel in percentages

### ISSUE THREAD

**Issue by predaytor** [radix-ui/themes#420]
LightningCSS does not understand the lightness oklch (L) parameter in the current syntax, but does work with percentages.

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.x%20%7B%5Cn%5Ct%2F*%20color%3A%20oklch(0.991%200.001%20277.7)%3B%20*%2F%5Cn%5Ctcolor%3A%20oklch(99.1%25%200.001%20277.7)%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
.x {
	color: oklch(0.991 0.001 277.7);
}
```
```css
.x {
	color: oklch(0.991 0.001 277.7);
}
```

Using percentages for lightness channel:
```css
.x {
	color: oklch(99.1% 0.001 277.7);
}
```
```css
.x {
	color: #fcfcfd;
	color: lab(98.9491% 0.0494123 -0.376499);
}
```
