### ISSUE TITLE
Wrong Letter Spacing (?)

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/themes#48]
The default letter spacing is:
```css
  --letter-spacing-1: 0.0025em;
  --letter-spacing-2: 0em;
  --letter-spacing-3: 0em;
  --letter-spacing-4: -0.0025em;
  --letter-spacing-5: -0.005em;
  --letter-spacing-6: -0.00625em;
  --letter-spacing-7: -0.0075em;
  --letter-spacing-8: -0.01em;
  --letter-spacing-9: -0.025em;
```

Isn't that backwards?

Components like `Avatar` and `Heading` scale letter spacing with their size. So as the component grows in size, the text becomes closer together.

Could well be intentional, just thought I would check.

Also: Not sure why 2 & 3 share the same value. It seems like the implementation of, for example, Avatar is leaking into the letter spacing constants.  Whereas, I think it would be better if Avatar did:
```css
    }
    &.rt-r-size-2 {
      ...
      letter-spacing: var(--letter-spacing-3);
    }
    &.rt-r-size-3 {
      ...
      letter-spacing: var(--letter-spacing-3);
    }
    &
```

Instead of:
https://github.com/radix-ui/themes/blob/392d620afe8cd6cc4489ed56e4289ca05c49986e/packages/radix-ui-themes/src/components/avatar.css#L62-L74

Also, if `Heading` **is** supposed to get closer as it grows in size, could simply do something like:
```css
      letter-spacing: calc(-var(--letter-spacing-9) - var(--heading-letter-spacing));
```

As always, just trying to understand
