### ISSUE TITLE
[TextField] `type="date"` causes misalignment on Firefox

### ISSUE THREAD

**Issue by SebKranz** [radix-ui/themes#527]
Reproducing example: https://codesandbox.io/p/sandbox/gallant-noether-kzwx4h?file=%2Fsrc%2FApp.tsx%3A6%2C12

<img width="389" alt="Screenshot 2024-06-13 at 13 44 03" src="https://github.com/radix-ui/themes/assets/33868262/00d6e0b7-c84d-4b38-8bf7-e15c3254da70">

It looks like this is due to the `white-space` property of `rt-reset`. 
As a workaround, adding the following line to the global css, fixes the issue.

```css
/** alternatively .rt-TextField[type="date"] */
input.rt-reset[type="date"] { 
  white-space: unset;
}
```
