### ISSUE TITLE
Segmented Control has broken classic variant

### ISSUE THREAD

**Issue by thien-do** [radix-ui/themes#635]
Since https://github.com/radix-ui/themes/pull/621, the "classic" variant no longer has its shadow, even when it is not disabled. This can be seen in [the playground of that PR](https://themes-playground-git-ksadd-segmented-control-disabled-workos.vercel.app/sink#segmented-control):

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/e2d13fd9-169a-4596-8b16-af77e97e1a01">

I understand from the design (mentioned in the PR) that the disable style is the same for both "classic" and "surface" variants. However, I believe it's not intentional for the "classic" style to lose its shadow when not being disabled due to this change.

In fact, the absence of shadow in disabled state is more likely to be an unintentional issue. The code change ([permalink](https://github.com/radix-ui/themes/pull/621/files#diff-4139588eeecd242c5d0a46572be1f302f65c5b3b77438dc0bad5e69d3d9e4e79L296-R317)) means the selectors will never match.

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/c2e947f2-22b5-4c03-8792-74f1184c1fc2">

We can see this from the final CSS as well:

```css
/* https://unpkg.com/browse/@radix-ui/themes@3.1.6/styles.css */
.rt-SegmentedControlRoot:where(.rt-variant-surface) :where(.rt-SegmentedControlItem:not([disabled])) :where(.rt-SegmentedControlIndicator)::before {
  box-shadow: 0 0 0 1px var(--gray-a4);
}

/* https://unpkg.com/browse/@radix-ui/themes@3.1.4/styles.css */
.rt-SegmentedControlRoot:where(.rt-variant-surface) :where(.rt-SegmentedControlIndicator)::before {
  box-shadow: 0 0 0 1px var(--gray-a4);
}
```

Because the structure of Segmented Control is that:

```
Root
- Item
- Item
- Indicator
```

The selector in 3.1.6 will never match anything, while the one in 3.1.4 does.
