### ISSUE TITLE
Theme reset is not applied to `<body>` tag using the 

### ISSUE THREAD

**Issue by ijxy** [radix-ui/themes#661]
The `styles.css` file includes this:

```css
.rt-reset:where(body, blockquote, dl, dd, figure, p) {
  margin: 0;
}
```

### Expectation

The above snippet would apply to the `<body>` and set margin to 0, when the app is set up in the suggested manner:

```ts
import { Theme } from "@radix-ui/themes";

export default function () {
  return (
    <html>
      <body>
        <Theme>
          <MyApp />
        </Theme>
      </body>
    </html>
  );
}
```

### Actual outcome

The `<body>` has default browser margins, ie the reset is not applied.

<img width="134" alt="image" src="https://github.com/user-attachments/assets/e6f7bb3e-6b01-4dda-8beb-796fea446e79" />
