### ISSUE TITLE
Negative inset classes don't exist

### ISSUE THREAD

**Issue by jgoz** [radix-ui/themes#735]
Inset properties (`top`, `left`, `right`, `bottom`) support negative values according to the prop defs, but the corresponding negative classnames are not defined.

I.e., I would expect these to be defined:

```css
.-rt-r-left-2 {
  left: calc(-1 * var(--space-2));
}
```
